### ISSUE TITLE
## Is your feature request related to a problem?

### ISSUE THREAD

**Issue by johnhenley** [johnhenley/Dnn.CommunityForums#4]
## Is your feature request related to a problem?
The Forum Content does not get indexed by DNN Search

## Describe the solution you'd like
Integrate the (once new) DNN Search.
See also: https://github.com/ActiveForums/ActiveForums/issues/12

__Originally posted by @Timo-Breumelhof in https://github.com/DNNCommunity/Dnn.CommunityForums/issues/94__

**Comment by Timo-Breumelhof** [comment]
@johnhenley I don't mind, but is there a reason you logged this too?

**Comment by Timo-Breumelhof** [comment]
Or.. are you going to implement this? ;-)

**Comment by johnhenley** [comment]
I'm still trying to get the hang of git. Although I've read a lot etc it still has me confused:) if I want to work in something within my local repo that addresses an issue in the parent repo, don't I want a "local" issue and a "local" pull request within my own repo to create a local branch and then pull back into my own repo before doing a pull request back to your repo? Or can I reference an upstream issue from my local repo? 

Any further git guidance or tutorials welcome:) I'm using this GitHub with visual studio 2019.
